apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "e7beffb0b55f6e5bc8b76f7353c5e3d9db791c915480bbbcbef08f0fa83960aa"
  JWT_REFRESH_SECRET: "a8cd8dbfdbdf359193320d97518dced936ff9f6d12059e16c76448334fcfc6ef263c261b5cf41457de958094bff46f786b87f80b1b956324b31188abd73590ca"
  ENCRYPTION_KEY: "e7beffb0b55f6e5bc8b76f7353c5e3d9db791c915480bbbcbef08f0fa83960aa"
  DB_PASSWORD: "postgres123"
  REDIS_PASSWORD: ""
  GOOGLE_CLIENT_ID: "placeholder"
  GOOGLE_CLIENT_SECRET: "placeholder"
  RAZORPAY_KEY_ID: "rzp_test_Sg9h9VKe7yrwX7"
  RAZORPAY_KEY_SECRET: "ze4YD28IrJQahL3GkS94s3iW"
  SMTP_USER: "your@gmail.com"
  SMTP_PASS: "your-app-password"
